-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN     "shippingCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalWithFees" DOUBLE PRECISION NOT NULL DEFAULT 0;
